// Mock fiel ao Excel "Resumo Mensal Pessoal — Justificações"

export const MOCK_RESUMO_PESSOAL_JUSTIFICACOES = {
  mes: "Agosto",
  ano: 2025,
  colaboradores: [
    { nome: "Adelino Pais da Costa",               empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: {} },
    { nome: "Amadou Diallo",                       empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "1:00",  sabados: "", hrTotais: "185:00", justificacoes: {} },
    { nome: "Ana Catarina Carvalho Costa",          empresa: "Manteivias",   diasTrab: "",  hrObra: "",       hrExtra: "",      sabados: "", hrTotais: "",       justificacoes: { LP: 23 } },
    { nome: "António sebastião Sá",                 empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: {} },
    { nome: "Anilzo dos Santos Vaz de Sousa",       empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: {} },
    { nome: "Basilio Manuel Soares Cruz",           empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Bruno José Afonso Batista",            empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Carlos Alberto Rodrigues Passos",      empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Carlos Martin Cruz",                   empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Daniel Osório Dias dos Santos",        empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Flávio Evanilson Guimarães M. Ramos", empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Hélder Manuel Martins Carvalheiro",    empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "7:00",  sabados: "", hrTotais: "191:00", justificacoes: {} },
    { nome: "Israel Gomes Pinto Junior",            empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "23:00", sabados: "", hrTotais: "207:00", justificacoes: { F: 1 } },
    { nome: "João Paulo Saraiva Leitão",            empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { FE: 5, F: 1 } },
    { nome: "Joaquim Ramos Figueiredo",             empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "23:00", sabados: "", hrTotais: "207:00", justificacoes: { F: 1 } },
    { nome: "Jose Manuel Gomes Martins",            empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { FE: 5, F: 1 } },
    { nome: "Kevin Brito Sá",                       empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Larbi Khatir",                         empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Maria de Fátima Fernandes Figueiredo", empresa: "Manteivias",   diasTrab: 20, hrObra: "160:00", hrExtra: "",      sabados: "", hrTotais: "160:00", justificacoes: { FE: 3, F: 1 } },
    { nome: "Mohamed Sabri Keddaoui",               empresa: "Manteivias",   diasTrab: 20, hrObra: "160:00", hrExtra: "",      sabados: "", hrTotais: "160:00", justificacoes: {} },
    { nome: "Paula Cristina da Fonseca Caçador",    empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Pedro Nuno Gomes Almeida",             empresa: "Manteivias",   diasTrab: 17, hrObra: "136:00", hrExtra: "",      sabados: "", hrTotais: "136:00", justificacoes: { FE: 7, F: 1 } },
    { nome: "Roboão Mae Larus Faria de Carvalho",   empresa: "Manteivias",   diasTrab: 23, hrObra: "184:00", hrExtra: "",      sabados: "", hrTotais: "184:00", justificacoes: { F: 1 } },
    { nome: "Sandra Isabel Lourenço Almeida",       empresa: "Manteivias",   diasTrab: "",  hrObra: "",       hrExtra: "",      sabados: "", hrTotais: "",       justificacoes: { BX: 20 } },
  ],
};